name: 'deploy to ecs'
description: 'deploy to ecs'
inputs:
  task_name:
    description: >
      ecs task name
    required: true
    type: string
  container_name:
    description: >
      ecs task container name
    default: ''
    required: true
    type: string
  image_name:
    description: >
      image name
    default: ''
    required: true
    type: string
  cluster_name:
    description: >
      ecs cluster name
    default: ''
    required: true
    type: string
  ecs_service_name:
    description: >
      ecs service name
    default: ''
    required: true
    type: string
  config-path:
    description: >-
      path to the ecr.json file which stores the variables for the instance
    required: false
    default: "./.github/ecr.json"
    type: string

runs:
  using: "composite"
  steps:
    - name: check ecr file
      run: |
        ls -la
      shell: bash
    - name: load variables
      id: load-vars
      uses: myriad-actions/load-variables@v2
      with:
        config-path: ${{ inputs.config-path }}
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: ${{ fromJson(steps.load-vars.outputs.vars).role-to-assume }}
        role-skip-session-tagging: true
        role-duration-seconds: 1380
        aws-region: ${{ fromJson(steps.load-vars.outputs.vars).aws-region }}
    - name: Download task definition
      run: |
        aws ecs describe-task-definition --task-definition ${{ inputs.task_name }} --query taskDefinition --region ${{ fromJson(steps.load-vars.outputs.vars).aws-region }} > task-definition.json
      shell: bash
    - name: Render Amazon ECS task definition
      id: render
      uses: aws-actions/amazon-ecs-render-task-definition@v1.2.0
      with:
        env-path: ${{ inputs.env-path }}
        task-definition: task-definition.json
        container-name: ${{ inputs.container_name }}
        image: ${{ inputs.image_name }}
        environment-variables: "LOG_LEVEL=info"
    - name: Deploy to Amazon ECS service
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1.4.10
      with:
        task-definition: ${{ steps.render.outputs.task-definition }}
        service: ${{ inputs.ecs_service_name }}
        cluster: ${{ inputs.cluster_name }}
